#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
TOTAL_MINUTES=23

# Repo clone is the working directory. Nothing in this wizard is written to
# .env or GitHub: MEM0_API_KEY is passed only to the feishu init process.
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT"
ENV_FILE=/dev/null
INIT_LOG=""
trap 'rm -f "${INIT_LOG:-}"' EXIT

banner "Feishu Agent setup"

stage "Node.js" 1
say "Feishu Agent needs Node.js 22.19 or newer."
if ! command -v node >/dev/null 2>&1; then
  warn "Node.js is not installed. Install 22.19 or newer, then re-run this script."
  exit 1
fi
if ! node -e 'const p=process.versions.node.split(".").map(Number); if (p[0]<22 || (p[0]===22 && p[1]<19)) process.exit(1)'; then
  warn "Node.js $(node -v) is too old. Install 22.19 or newer, then re-run this script."
  exit 1
fi
say "Node.js $(node -v) is new enough."
pause

stage "Build and link" 5
say "Install dependencies, compile, and link the feishu command from this checkout."
npm install
npm run build
npm link
say "feishu is linked from this checkout."
pause

stage "Feishu login" 4
say "Install @larksuite/cli. Do not install the unrelated npm package named lark-cli."
if ! command -v lark-cli >/dev/null 2>&1; then
  npm i -g @larksuite/cli
fi
if confirm "Are you already logged in with lark-cli?"; then
  say "Keeping the existing lark-cli login."
else
  say "lark-cli will print a verification URL and wait. Approve it in the browser, then return here."
  lark-cli auth login
fi

stage "Model login" 4
say "Feishu reads model credentials from ordinary Pi and disables its own /login."
if ! command -v pi >/dev/null 2>&1; then
  npm i -g @earendil-works/pi-coding-agent
fi
step "Open another terminal and run: pi"
step "Type /login and press Enter."
step "Choose Sign in with an API key, or Sign in with an account."
step "Select the provider, then paste the key or finish the browser login."
step "Type /quit to leave Pi."
pause "Press Enter after Pi says the login succeeded."
if ! models=$(node --input-type=module <<'EOF'
import { ModelRuntime } from "@earendil-works/pi-coding-agent";
import { homedir } from "node:os";
import { join } from "node:path";
const piHome = join(homedir(), ".pi", "agent");
const runtime = await ModelRuntime.create({ authPath: join(piHome, "auth.json"), modelsPath: join(piHome, "models.json"), allowModelNetwork: false });
const models = (await runtime.getAvailable()).map((entry) => `${entry.provider}/${entry.id}`);
if (models.length === 0) process.exit(2);
process.stdout.write(models.join("\n"));
EOF
); then
  warn "No authenticated model is available. Finish /login in pi, then re-run this script."
  exit 1
fi
say "Authenticated models:"
while IFS= read -r line; do say "$line"; done <<< "$models"
note "Use one of those provider/model values in the next step. This script does not copy the key."

stage "Mem0 API key" 3
say "feishu init needs MEM0_API_KEY. This script does not write it to disk."
open_url "https://app.mem0.ai/login"
step "Sign in, or create a Mem0 Platform account."
step "Open Settings, then API Keys."
step "Generate a new key and copy it. It is shown once."
MEM0_API_KEY=""
while [[ -z "$MEM0_API_KEY" ]]; do
  ask_secret MEM0_API_KEY "Paste the Mem0 API key:"
  [[ -n "$MEM0_API_KEY" ]] || warn "The key was empty."
done
note "Held in this process only. Re-running the script asks again."

stage "Initialize" 5
say "Choose the identity, model, and thinking level stored under ~/.feishu-agent."
note "An existing identity and model are kept. This script does not pass --reset-*."
IDENTITY=""
while true; do
  ask IDENTITY "Stable memory identity:"
  if [[ -n "$IDENTITY" && "$IDENTITY" != -* && ! "$IDENTITY" =~ [[:space:]] ]]; then break; fi
  warn "Identity must be non-empty, contain no spaces, and not start with -."
done
MODEL=""
while true; do
  ask MODEL "Authenticated model (provider/model):"
  if [[ "$MODEL" =~ ^[^[:space:]/]+/[^[:space:]/]+$ && "$MODEL" != -* ]]; then break; fi
  warn "Use provider/model, for example the provider you just logged into."
done
THINKING=""
while true; do
  ask THINKING "Thinking level (off, minimal, low, medium, high, xhigh). Enter for medium:"
  [[ -z "$THINKING" ]] && THINKING=medium
  case "$THINKING" in
    off|minimal|low|medium|high|xhigh) break ;;
    *) warn "Thinking level must be one of: off, minimal, low, medium, high, xhigh." ;;
  esac
done
if ! confirm "Run feishu init now? It writes ~/.feishu-agent and checks Mem0."; then
  warn "Stopped before init. The Mem0 key was not saved."
  exit 1
fi
INIT_LOG=$(mktemp)
MEM0_API_KEY="$MEM0_API_KEY" node "$ROOT/dist/src/cli.js" init \
  --identity "$IDENTITY" --model "$MODEL" --thinking "$THINKING" | tee "$INIT_LOG"

stage "Keep the Mem0 key in your shell" 1
say "Init is done. The Mem0 key was not written to disk."
say "In every new terminal, export MEM0_API_KEY before you run feishu."
note "Do not commit the key or put it in SOUL.md or USER.md."
if [[ -s "$INIT_LOG" ]]; then
  say "Init summary:"
  while IFS= read -r line; do say "$line"; done < "$INIT_LOG"
fi
pause

finish
say "In every new terminal, export MEM0_API_KEY before you run feishu."
note "Do not commit the key or put it in SOUL.md or USER.md."
if [[ -s "${INIT_LOG:-}" ]]; then
  while IFS= read -r line; do say "$line"; done < "$INIT_LOG"
fi
